version: "3.3"
services:
  rocket-web-app-beta-dev:
    build: 
      context: .
      dockerfile: "dockerfile-rocket"
    image: "rocket-web-app-beta-dev:latest"
    container_name: "rocket-web-app-beta-dev"
    depends_on:
      - rocket-web-app-beta-ubuntu
    ports:
      - 8081:8000
    profiles:
      - dev
  rocket-web-app-beta:
    build: 
      context: .
      dockerfile: "dockerfile-rocket"
    image: "rocket-web-app-beta-prod:latest"
    container_name: "rocket-web-app-beta-prod"
    depends_on:
      - rocket-web-app-beta-ubuntu
    ports:
      - 8080:8000
    profiles:
      - prod
  rocket-web-app-beta-ubuntu:
    build: 
      context: .
      dockerfile: "dockerfile-ubuntu"
    image: "rocket-web-app-beta-ubuntu:latest"
    container_name: "rocket-web-app-beta-ubuntu"